# -*- mode: ruby -*-
# vi: set ft=ruby :

virtualbox_vm_basedir = '/ING/VirtualBox VMs'

cephmons = [
    {
        :name      => "cephmon1",
        :ipaddress => "192.168.33.81",
        :hostname  => "cephmon1.cluster1"
    },
    {
        :name      => "cephmon2",
        :ipaddress => "192.168.33.82",
        :hostname  => "cephmon2.cluster1"
    },
    {
        :name      => "cephmon3",
        :ipaddress => "192.168.33.83",
        :hostname  => "cephmon3.cluster1"
    }
]

cephnodes = [
    {
        :name         => "cephnode1",
        :ipaddress    => "192.168.33.84",
        :hostname     => "cephnode1.cluster1",
        :file_to_disk => "ceph_osd_disk1.vdi"
    },
    {
        :name         => "cephnode2",
        :ipaddress    => "192.168.33.85",
        :hostname     => "cephnode2.cluster1",
        :file_to_disk => "ceph_osd_disk1.vdi"
    },
    {
        :name         => "cephnode3",
        :ipaddress    => "192.168.33.86",
        :hostname     => "cephnode3.cluster1",
        :file_to_disk => "ceph_osd_disk1.vdi"
    }
]

Vagrant.configure(2) do |config|
    config.vm.box = "ceph/centos7"
    cephmons.each do |opts|
        config.vm.define opts[:name] do |cephmon|
            cephmon.vm.network "private_network", ip: opts[:ipaddress]
            cephmon.vm.synced_folder ".","/vagrant", type: "virtualbox", disabled: true
            cephmon.vm.synced_folder ".","/home/vagrant/sync", type: "virtualbox", disabled: true
            cephmon.vm.provider "virtualbox" do |vb|
                vb.memory = 1024
                vb.name = opts[:name]
            end
            cephmon.vm.hostname = opts[:hostname]
            cephmon.vm.provision "shell",
                inline: "echo '192.168.33.100 learning.puppetlabs.vm' >> /etc/hosts"
            cephmon.vm.provision "shell",
                inline: "curl -k https://learning.puppetlabs.vm:8140/packages/current/install.bash | sudo bash"
        end
    end
   
    cephnodes.each do |opts|
        config.vm.define opts[:name] do |cephnode|
            cephnode.vm.network "private_network", ip: opts[:ipaddress]
            cephnode.vm.synced_folder ".","/vagrant", type: "virtualbox", disabled: true
            cephnode.vm.synced_folder ".","/home/vagrant/sync", type: "virtualbox", disabled: true
            cephnode.vm.provider "virtualbox" do |vb|
                vb.memory = 1024
                vb.name = opts[:name]
                disk = "#{virtualbox_vm_basedir}/#{opts[:name]}/#{opts[:file_to_disk]}"
                #unless File.exist?(disk)
                #    vb.customize ['createhd', '--filename', disk, '--variant', 'Standard', '--size', 1 * 1024]
                #end
                #vb.customize ['storageattach', :id,  '--storagectl', 'IDE Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', disk]
            end
            cephnode.vm.hostname = opts[:hostname]
            cephnode.vm.provision "shell",
                inline: "echo '192.168.33.100 learning.puppetlabs.vm' >> /etc/hosts"
            cephnode.vm.provision "shell",
                inline: "curl -k https://learning.puppetlabs.vm:8140/packages/current/install.bash | sudo bash"
        end
    end
   
   config.vm.define :cephmaster do |cephmaster|
      cephmaster.vm.network "private_network", ip: "192.168.33.80"
      cephmaster.vm.synced_folder ".","/vagrant", type: "virtualbox", disabled: true
      cephmaster.vm.synced_folder ".","/home/vagrant/sync", type: "virtualbox", disabled: true
      cephmaster.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
        vb.name = "cephmaster"
      end
      cephmaster.vm.hostname = "cephmaster.cluster1"	  
      cephmaster.vm.provision "shell",
         inline: "echo '192.168.33.100 learning.puppetlabs.vm' >> /etc/hosts"
      cephmaster.vm.provision "shell",
         inline: "curl -k https://learning.puppetlabs.vm:8140/packages/current/install.bash | sudo bash"
   end
    
end
